---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
configMapGenerator:
  - name: ${APP}-gatus-ep
    files:
      - config.yaml=./config.yaml
    options:
      annotations:
        gatus.home-operations.com/enabled: "true"
      labels:
        gatus.io/enabled: "true"
generatorOptions:
  disableNameSuffixHash: true
